### ISSUE TITLE
"Bad word" censorship

### ISSUE THREAD

**Issue by tacyarg** [DaltonWebDev/console.chat#4]
https://github.com/DaltonWebDev/console.chat/blob/7a8ab35408de019251ec221b29053da7471bc174/api/send.php#L3-L21

I suggest we remove these defaults from the project as they are infringing on freedom of speech. People should be allowed to chat using whatever words they so choose.
Enforcing centralized control of the speech is arguably bad for the free flow of ideas.

**Comment by DaltonWebDev** [comment]
While I understand your point of view, this repo is a direct reflection of the production instance. People are free to fork this repo and remove this filter, but console.chat is a private platform and well within its means to enforce these bans. Thanks.
